
package com.adanyc.spring.soap.api.sunat;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "billService", targetNamespace = "http://service.sunat.gob.pe")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BillService {


    /**
     * 
     * @param rucComprobante
     * @param serieComprobante
     * @param numeroComprobante
     * @param tipoComprobante
     * @return
     *     returns com.adanyc.spring.soap.api.sunat.StatusResponse
     */
    @WebMethod(action = "urn:getStatusCdr")
    @WebResult(name = "statusCdr", targetNamespace = "")
    @RequestWrapper(localName = "getStatusCdr", targetNamespace = "http://service.sunat.gob.pe", className = "com.adanyc.spring.soap.api.sunat.GetStatusCdr")
    @ResponseWrapper(localName = "getStatusCdrResponse", targetNamespace = "http://service.sunat.gob.pe", className = "com.adanyc.spring.soap.api.sunat.GetStatusCdrResponse")
    @Action(input = "urn:getStatusCdr", output = "http://service.sunat.gob.pe/billService/getStatusCdrResponse")
    public StatusResponse getStatusCdr(
        @WebParam(name = "rucComprobante", targetNamespace = "")
        String rucComprobante,
        @WebParam(name = "tipoComprobante", targetNamespace = "")
        String tipoComprobante,
        @WebParam(name = "serieComprobante", targetNamespace = "")
        String serieComprobante,
        @WebParam(name = "numeroComprobante", targetNamespace = "")
        Integer numeroComprobante);

    /**
     * 
     * @param rucComprobante
     * @param serieComprobante
     * @param numeroComprobante
     * @param tipoComprobante
     * @return
     *     returns com.adanyc.spring.soap.api.sunat.StatusResponse
     */
    @WebMethod(action = "urn:getStatus")
    @WebResult(name = "status", targetNamespace = "")
    @RequestWrapper(localName = "getStatus", targetNamespace = "http://service.sunat.gob.pe", className = "com.adanyc.spring.soap.api.sunat.GetStatus")
    @ResponseWrapper(localName = "getStatusResponse", targetNamespace = "http://service.sunat.gob.pe", className = "com.adanyc.spring.soap.api.sunat.GetStatusResponse")
    @Action(input = "urn:getStatus", output = "http://service.sunat.gob.pe/billService/getStatusResponse")
    public StatusResponse getStatus(
        @WebParam(name = "rucComprobante", targetNamespace = "")
        String rucComprobante,
        @WebParam(name = "tipoComprobante", targetNamespace = "")
        String tipoComprobante,
        @WebParam(name = "serieComprobante", targetNamespace = "")
        String serieComprobante,
        @WebParam(name = "numeroComprobante", targetNamespace = "")
        Integer numeroComprobante);

}
